### ISSUE TITLE
Formatting leaves extra spaces in front of words

### ISSUE THREAD

**Issue by TangentFoxy** [andrewlalis/BlockBookBinder#3]
I noticed with a test run that a lot of lines after being broken up had extra spaces at the beginning of a line.

**Comment by andrewlalis** [comment]
I haven't really supported this app in a long time, but could you give me some more details like:

- Were the spaces added in the preview text, or only once they're pasted into the book.
- What version of minecraft are you running?

**Comment by TangentFoxy** [comment]
I didn't bother trying to paste it into a book after seeing the spaces. I assumed the preview was accurate, and therefore unacceptable.

Went back and ran it again with a short story of mine to give you a screenshot:
![image](https://github.com/andrewlalis/BlockBookBinder/assets/15093567/62052fbe-1366-4345-944f-f30c8f025b78)

**Comment by andrewlalis** [comment]
Should be fixed in the latest release: https://github.com/andrewlalis/BlockBookBinder/releases/tag/1.3.0
