### ISSUE TITLE
Java exception error

### ISSUE THREAD

**Issue by BaldousHuxley** [andrewlalis/BlockBookBinder#4]
First of all I'd like to say that I'm a huge fan of this application, as I've been searching for something like this for ages. Sadly, when launching the latest version (1.3.0) I get the error depicted below:

![jerror](https://github.com/andrewlalis/BlockBookBinder/assets/138396952/1481893a-8489-435b-8bd5-692f0ac9acd5)

Interstingly enough, after a bit of digging I found out that the previous version of the .jar file (1.1.0) runs perfectly fine. I tried to fix the error by following some guides online, but to no avail. Also the fact that the previous version works could suggest the problem lies in the file itself (although I'm no expert on the matter). I'm on Windows 10 with Java 20 environment, so I assume compatibility is not the problem. I really hope this is fixable, but even tips on what could be the issue would be of great help. Thanks

Edit: I persevered in finding more information regarding the issue to help the troubleshooting process, and managed to output the error log into a .txt  file, which I attach here hoping it helps:

[error.txt](https://github.com/andrewlalis/BlockBookBinder/files/12049587/error.txt)

**Comment by BaldousHuxley** [comment]
That's unfortunate, I hope you didn't lose anything of value.

**Comment by andrewlalis** [comment]
Should be fixed as of release version 1.3.1
