### ISSUE TITLE
The 1.1.0 version worked great; the 1.3.0 or 1.3.1 both close without notification

### ISSUE THREAD

**Issue by Griffon-Prime** [andrewlalis/BlockBookBinder#6]
Wanted to see what was new with the 1.3.1 version but when I try to run it, the javaw.exe opens for a second and closes without notification. The 1.1.0 still works with no issues.

If I can somehow run it in a way to produce a log of the error, let me know. There is no update on screen; just a brief existence in Task Manager.

**Comment by andrewlalis** [comment]
Run the program from the terminal using `java -jar <jarfile>`; that will show output.

**Comment by Griffon-Prime** [comment]
Perfect. It appears I have an older version of Java because it says it only supports versions up to class file 60.0 and your program is looking for class file version 61.0. Not sure if backward compatibility is your goal, or maybe a noisier notification if it stops running, but that is my issue. I'll update my java and try again. Here is the text of the error:

Error: LinkageError occurred while loading main class nl.andrewlalis.blockbookbinder.BlockBookBinder
        java.lang.UnsupportedClassVersionError: nl/andrewlalis/blockbookbinder/BlockBookBinder has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

**Comment by Griffon-Prime** [comment]
Upgraded to JDK 21 and no issues now. Thanks.

**Comment by andrewlalis** [comment]
Yep, I'm pretty sure I mentioned somewhere in the readme that at least java 17 was required. Now that version 21 is out, I might like to upgrade again, but good to see it's resolved.

**Comment by winderine** [comment]
Okay, with Java 21 I still had this window not opening issue but opening it through the command line just worked. Java is so weird.
