### ISSUE TITLE
Support for Cyrillic

### ISSUE THREAD

**Issue by WoofWolfGG** [andrewlalis/BlockBookBinder#7]
It's a great program, but I had a problem with the Cyrillic. The program just doesn't accept it and it's very sad. I would be very happy and grateful if you could add support for Cyrillic.

**Comment by andrewlalis** [comment]
Sorry, but at the moment, I don't really have any experience with the cyrillic alphabet, and the character sizes are not well-documented anywhere I could find yet. If you're able, you can fork it and add support, and it would be much appreciated.
